### ISSUE TITLE
I would like to contribute to contribute-2022 json file please asign this to me

### ISSUE THREAD

**Issue by gajanansr** [reactplay/hacktoberfest#12]
### Contributor's Name

Gajanan Rathod

### GitHub Username

gajanansr

### Description

na

### Contribution Category

low-code

### What was it about?

writing

### Select the exact contribution you did

copy-editing

### Link to your Contribution

na

### Code of Conduct

- [X] I agree to the above statement

**Comment by joshi-kaushal** [comment]
Hello! Whare are you planning t do, can you please elaborate?

**Comment by joshi-kaushal** [comment]
Hello @gajanansr! What are you planning to do? Can you please elaborate?

**Comment by gajanansr** [comment]
Done please merge the pull request
