### ISSUE TITLE
Form Validation Blog Post

### ISSUE THREAD

**Issue by daryllukas** [reactplay/hacktoberfest#16]
### Contributor's Name

Daryl Lukas

### GitHub Username

daryllukas

### Description

I wrote a couple on blog posts on Form Validation in React and React Native using Formik.

### Contribution Category

low-code

### What was it about?

advocacy

### Select the exact contribution you did

thread, blogs

### Link to your Contribution

https://hashnode.com/draft/635a42e801e68714e4841fe2

### Code of Conduct

- [X] I agree to the above statement

**Comment by joshi-kaushal** [comment]
Hi @daryllukas!

We are accepting low/no-code contributions made for the ReactPlay community.

If you could publish your next blog on [blog.reactplay.io](blog.reactplay.io), we can accept it as a valid contribution.

I will close this issue after the next two days if you don't publish/submit a new blog for ReactPlay blog.
But don't worry. You can always create a new issue if you publish one.

**Comment by daryllukas** [comment]
@joshi-kaushal Can't I republish the same one? I've published it on [Hashnode](https://daryllukas.hashnode.dev/form-validation-in-react-using-formik). Also, how do I get it on the ReactPlay blog?

**Comment by joshi-kaushal** [comment]
Congratulations! Your blog is published. You can read it [here](https://blog.reactplay.io/form-validation-in-react-using-formik).

I am assigning you this issue. Make sure you add the published blog's link in the JSON.
