### ISSUE TITLE
Typos fixed

### ISSUE THREAD

**Issue by mersonfufu** [reactplay/hacktoberfest#21]
### Contributor's Name

Hemerson

### GitHub Username

mersonfufu

### Description

Just some typos fixed

### Contribution Category

no-code

### What was it about?

writing

### Select the exact contribution you did

thread

### Link to your Contribution

https://github.com/reactplay/hacktoberfest/pull/17

### Code of Conduct

- [X] I agree to the above statement

**Comment by joshi-kaushal** [comment]
hi, could you provide a valid link to verify your submission?

**Comment by mersonfufu** [comment]
https://github.com/reactplay/hacktoberfest/blob/main/README.md

Sorry. I don't know what kind link is expected :)

**Comment by joshi-kaushal** [comment]
oh. your contribution was merged already. my bad.

please provide [this](https://github.com/reactplay/hacktoberfest/pull/17) link when you will add your data to the JSON file.

**Comment by mersonfufu** [comment]
Sorry. I've posted this link but, 4 some reason, it shrink. Anyway, thanks, friend

![link](https://user-images.githubusercontent.com/39348069/198107158-aa213714-4759-42ea-bf33-dbbc2b69c426.png)

**Comment by joshi-kaushal** [comment]
Oh yes, that's how they are supposed to work. No worries. It was a misunderstanding on my end. 

Let's merge your PR ASAP! 🚀

**Comment by joshi-kaushal** [comment]
hi @mersonfufu, any update? You just need to make a PR. Let me know if you are stuck.

**Comment by mersonfufu** [comment]
Hi, my friend. You already merge my PR. Check it in here:

https://github.com/reactplay/hacktoberfest/pull/17

**Comment by joshi-kaushal** [comment]
oh! it was not merged by me so i got confused. NVM. 

The other four repositories you mentioned are maintained by @atapas. I can't merge them.
