### ISSUE TITLE
Lists and Keys Blog Post

### ISSUE THREAD

**Issue by daryllukas** [reactplay/hacktoberfest#24]
### Contributor's Name

Daryl Lukas

### GitHub Username

daryllukas

### Description

I wrote a post about automatically assigning keys when rendering a list of children in React.

### Contribution Category

low-code

### What was it about?

writing

### Select the exact contribution you did

blogs

### Link to your Contribution

https://hashnode.com/draft/635be9e793b35e2fb5d817db

### Code of Conduct

- [X] I agree to the above statement

**Comment by joshi-kaushal** [comment]
_Hi, thanks for your submission. Could you please give me the link where it was posted previously?

Also, we don't allow direct or indirect advertisements on our blogs. I am removing the last paragraph from your article. Could you please replace it with a *conclusion* or wrapping up* section? That would be useful._

**Comment by daryllukas** [comment]
Here is the [previous post](https://daryllukas.hashnode.dev/lists-and-keys-in-react)

**Comment by daryllukas** [comment]
How do I avoid the duplicate key warning if adding more that one contribution?


![image](https://user-images.githubusercontent.com/1014489/198920838-97f24772-eb7a-4ca1-ba4a-8aeb35d63d5b.png)

**Comment by joshi-kaushal** [comment]
make it an array of objects. 

```js
"daryllukas": [
  {  // data 1  },
  {  // data 2  }
]

**Comment by daryllukas** [comment]
> make it an array of objects.
> 
> ```js
> "daryllukas": [
>   {  // data 1  },
>   {  // data 2  }
> ]
> ```

Oh right! Silly me.. Thank you very much @joshi-kaushal

**Comment by joshi-kaushal** [comment]
It is scheduled for tomorrow. Put the same draft link for now. We will update it once its published.
