### ISSUE TITLE
Add writeonce blog contribution

### ISSUE THREAD

**Issue by ammaaraslam** [reactplay/hacktoberfest#27]
### Contributor's Name

Ammaar Aslam

### GitHub Username

ammaaraslam

### Description

Wrote a blog on blog.reactplay.io about my HACK-R-PLAY submission, WriteOnce

### Contribution Category

no-code

### What was it about?

writing

### Select the exact contribution you did

blogs

### Link to your Contribution

https://blog.reactplay.io/introducing-writeonce-a-markdown-editor-for-devs-who-blog

### Code of Conduct

- [X] I agree to the above statement

**Comment by joshi-kaushal** [comment]
closing the issue since pr already got merged.
